// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package enum

const telemetryInfo = "azsdk-go-enum/<version>"

type Enum2 string

const (
	Enum2ContentType  Enum2 = "content_type"
	Enum2Etag         Enum2 = "etag"
	Enum2Key          Enum2 = "key"
	Enum2Label        Enum2 = "label"
	Enum2LastModified Enum2 = "last_modified"
	Enum2Locked       Enum2 = "locked"
	Enum2Tags         Enum2 = "tags"
	Enum2Value        Enum2 = "value"
)

// PossibleEnum2Values returns the possible values for the Enum2 const type.
func PossibleEnum2Values() []Enum2 {
	return []Enum2{
		Enum2ContentType,
		Enum2Etag,
		Enum2Key,
		Enum2Label,
		Enum2LastModified,
		Enum2Locked,
		Enum2Tags,
		Enum2Value,
	}
}

// ToPtr returns a *Enum2 pointing to the current value.
func (c Enum2) ToPtr() *Enum2 {
	return &c
}

type Get0ItemsItem string

const (
	Get0ItemsItemContentType  Get0ItemsItem = "content_type"
	Get0ItemsItemEtag         Get0ItemsItem = "etag"
	Get0ItemsItemKey          Get0ItemsItem = "key"
	Get0ItemsItemLabel        Get0ItemsItem = "label"
	Get0ItemsItemLastModified Get0ItemsItem = "last_modified"
	Get0ItemsItemLocked       Get0ItemsItem = "locked"
	Get0ItemsItemTags         Get0ItemsItem = "tags"
	Get0ItemsItemValue        Get0ItemsItem = "value"
)

// PossibleGet0ItemsItemValues returns the possible values for the Get0ItemsItem const type.
func PossibleGet0ItemsItemValues() []Get0ItemsItem {
	return []Get0ItemsItem{
		Get0ItemsItemContentType,
		Get0ItemsItemEtag,
		Get0ItemsItemKey,
		Get0ItemsItemLabel,
		Get0ItemsItemLastModified,
		Get0ItemsItemLocked,
		Get0ItemsItemTags,
		Get0ItemsItemValue,
	}
}

// ToPtr returns a *Get0ItemsItem pointing to the current value.
func (c Get0ItemsItem) ToPtr() *Get0ItemsItem {
	return &c
}

type Head0ItemsItem string

const (
	Head0ItemsItemA Head0ItemsItem = "a"
	Head0ItemsItemB Head0ItemsItem = "b"
	Head0ItemsItemC Head0ItemsItem = "c"
	Head0ItemsItemD Head0ItemsItem = "d"
	Head0ItemsItemE Head0ItemsItem = "e"
	Head0ItemsItemF Head0ItemsItem = "f"
	Head0ItemsItemG Head0ItemsItem = "g"
	Head0ItemsItemH Head0ItemsItem = "h"
)

// PossibleHead0ItemsItemValues returns the possible values for the Head0ItemsItem const type.
func PossibleHead0ItemsItemValues() []Head0ItemsItem {
	return []Head0ItemsItem{
		Head0ItemsItemA,
		Head0ItemsItemB,
		Head0ItemsItemC,
		Head0ItemsItemD,
		Head0ItemsItemE,
		Head0ItemsItemF,
		Head0ItemsItemG,
		Head0ItemsItemH,
	}
}

// ToPtr returns a *Head0ItemsItem pointing to the current value.
func (c Head0ItemsItem) ToPtr() *Head0ItemsItem {
	return &c
}
