// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package enum

// AzureAppConfigurationCheckKeyValuesAOptions contains the optional parameters for the AzureAppConfiguration.CheckKeyValuesA method.
type AzureAppConfigurationCheckKeyValuesAOptions struct {
	// abc's
	OtherSelect []Head0ItemsItem
}

// AzureAppConfigurationCheckKeyValuesOptions contains the optional parameters for the AzureAppConfiguration.CheckKeyValues method.
type AzureAppConfigurationCheckKeyValuesOptions struct {
	// .
	Foo []Enum2
}

// AzureAppConfigurationGetKeyValuesOptions contains the optional parameters for the AzureAppConfiguration.GetKeyValues method.
type AzureAppConfigurationGetKeyValuesOptions struct {
	// .
	Foo []Get0ItemsItem
}
