// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package enum

import "net/http"

// AzureAppConfigurationCheckKeyValuesAResponse contains the response from method AzureAppConfiguration.CheckKeyValuesA.
type AzureAppConfigurationCheckKeyValuesAResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// AzureAppConfigurationCheckKeyValuesResponse contains the response from method AzureAppConfiguration.CheckKeyValues.
type AzureAppConfigurationCheckKeyValuesResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// AzureAppConfigurationGetKeyValuesResponse contains the response from method AzureAppConfiguration.GetKeyValues.
type AzureAppConfigurationGetKeyValuesResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}
